Repository Ky7Org/weight-loss-consultant, pull requests merged in 2021-10, with the labels that each got.

#39 FUSE-62 [SWD-391] implement session for Phuong's mobile app
  apps/weight-loss-consultant-mobile/assets/logo/9-dots-icon.svg
  apps/weight-loss-consultant-mobile/lib/constants/role_enum.dart
  apps/weight-loss-consultant-mobile/lib/models/account_model.dart
  apps/weight-loss-consultant-mobile/lib/pages/authentication/login_page.dart
  apps/weight-loss-consultant-mobile/lib/pages/components/customer_drawer.dart
  apps/weight-loss-consultant-mobile/lib/pages/customer/customer_home_page.dart
  apps/weight-loss-consultant-mobile/lib/routings/route_generator.dart
  apps/weight-loss-consultant-mobile/lib/services/login_service.dart
  apps/weight-loss-consultant-mobile/pubspec.lock
  apps/weight-loss-consultant-mobile/pubspec.yaml
Labels: ready to merge, ready to review

#41 FUSE-64 Implement level mechanism for mobile app
  apps/weight-loss-consultant-mobile-hci-version/lib/screens/customer_main_screen.dart
  apps/weight-loss-consultant-mobile-hci-version/lib/screens/today_diet_screen.dart
  apps/weight-loss-consultant-mobile-hci-version/lib/screens/today_exercise_screen.dart
  apps/weight-loss-consultant-mobile-hci-version/lib/services/diet_service.dart
  apps/weight-loss-consultant-mobile-hci-version/lib/services/exercise_service.dart
Labels: ready to merge, ready to review

#43 [FUSE-60] Implementing Search functionality for UI
  apps/weight-loss-consultant-health-mgnt-api/src/assets/.env
  apps/weight-loss-consultant-ui/src/components/ListUser/ListUser.jsx
  apps/weight-loss-consultant-ui/src/components/ListUser/TableUser/TableUser.css
  apps/weight-loss-consultant-ui/src/components/ListUser/TableUser/TableUser.jsx
  apps/weight-loss-consultant-ui/src/components/header/AppHeader/AppHeader.jsx
  apps/weight-loss-consultant-ui/src/components/header/AppHeader/AppHeader.module.scss
  apps/weight-loss-consultant-ui/src/components/header/headerAuth.jsx
  apps/weight-loss-consultant-users-mgnt-api/src/app/auth/auth.controller.ts
Labels: ready to review

#37 [FUSE-59] Implementing Filter, Searching for Users Management
  apps/weight-loss-consultant-users-mgnt-api/src/app/auth/login.res.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/constants/enums.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/controllers/admin.controller.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/controllers/customer.controller.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/controllers/sorting-filtering.controller.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/controllers/trainer.controller.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/dtos/pagination/paginated-result.dto.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/dtos/pagination/pagination.dto.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/modules/app.module.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/modules/sorting-filtering.module.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/services/impl/admin.service.impl.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/services/impl/customer.service.impl.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/services/impl/trainer.service.impl.ts
  apps/weight-loss-consultant-users-mgnt-api/src/app/services/sorting-filtering.service.ts
  apps/weight-loss-consultant-users-mgnt-api/src/assets/.env
  apps/weight-loss-consultant-users-mgnt-api/src/main.ts
Labels: ready to review, WIP

#74 [FUSE-83] - Fix bug users can’t authenticated with Firebase Authentication
  apps/weight-loss-consultant-authentication/src/app/controllers/app.controller.ts
  apps/weight-loss-consultant-authentication/src/app/modules/authentication.module.ts
  apps/weight-loss-consultant-authentication/src/app/services/authentication.service.ts
  apps/weight-loss-consultant-authentication/src/app/services/firebase-auth.service.ts
  apps/weight-loss-consultant-authentication/src/main.ts
  apps/weight-loss-consultant-gateway/src/app/auth/auth.module.ts
  apps/weight-loss-consultant-gateway/src/app/auth/firebase-auth.guard.ts
  apps/weight-loss-consultant-gateway/src/app/auth/strategies/firebase-auth.strategy.ts
  apps/weight-loss-consultant-gateway/src/app/controllers/authentication/authentication.controller.ts
  apps/weight-loss-consultant-gateway/src/app/services/authentication/authentication.service.ts
  firebase.config.json
Labels: ready to merge, ready to review

#76 [FUSE-85] - Implement BCrypt Password Hash
  apps/common/utils.ts
  apps/weight-loss-consultant-authentication/src/app/services/authentication.service.ts
  apps/weight-loss-consultant-gateway/src/app/modules/app.module.ts
  package-lock.json
Labels: ready to merge, ready to review

#79 [FUSE-89] - Implement deploy script for API/UI
  package.json
Labels: ready to merge, ready to review
